wandb_version: 1

alsologtostderr:
  desc: null
  value: false
delta_threshold:
  desc: null
  value: 0.5
hbm_oom_exit:
  desc: null
  value: true
log_dir:
  desc: null
  value: ''
logger_levels:
  desc: null
  value: {}
logtostderr:
  desc: null
  value: false
only_check_args:
  desc: null
  value: false
op_conversion_fallback_to_while_loop:
  desc: null
  value: true
pdb:
  desc: null
  value: false
pdb_post_mortem:
  desc: null
  value: false
profile_file:
  desc: null
  value: null
run_with_pdb:
  desc: null
  value: false
run_with_profiling:
  desc: null
  value: false
runtime_oom_exit:
  desc: null
  value: true
showprefixforinfo:
  desc: null
  value: true
stderrthreshold:
  desc: null
  value: fatal
test_random_seed:
  desc: null
  value: 301
test_randomize_ordering_seed:
  desc: null
  value: ''
test_srcdir:
  desc: null
  value: ''
test_tmpdir:
  desc: null
  value: /tmp/slurm/1562430/absl_testing
tt_check_filter:
  desc: null
  value: false
tt_single_core_summaries:
  desc: null
  value: false
use_cprofile_for_profiling:
  desc: null
  value: true
v:
  desc: null
  value: -1
verbosity:
  desc: null
  value: -1
xml_output_file:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722018675
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 55
      - 105
      3:
      - 4
      - 16
      - 23
      - 34
      - 42
      4: 3.10.13
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
